### ISSUE TITLE
DialogueBox doesn't consume touch input events

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-turn-based-rpg#113]

**Comment by NathanLovato** [comment]
I don't know. The input sometimes passes through the buttons and it shouldn't. I've experimented with GUI input, Control.accept_event to consume them, but sometimes it doesn't work. Might be a bug with 3.1 alpha. Touch events always pass through the panel even if it's set to stop it.

Also I have trouble getting touch emulation from mouse and vice versa. Need to do a test project to see if it's broken in 3.1 alpha 2

**Comment by Piddau** [comment]
There was this [issue](https://github.com/godotengine/godot/pull/21386) that was fixed in 3.1 alpha 3.

Perhaps this fixed it?

**Comment by NathanLovato** [comment]
Should be closed with https://github.com/GDquest/godot-turn-based-rpg/pull/127
