### ISSUE TITLE
[question] Whats the future of this project?

### ISSUE THREAD

**Issue by Jummit** [GDquest/godot-turn-based-rpg#12]
Whats the future of this project? There are currently no issues which makes me think that there is not much to be done here. If there is anything I could do, I would love to know!

**Comment by NathanLovato** [comment]
I'm busy wrapping up the Godot course, I'll open new issues after I've finished some of that work

**Comment by Jummit** [comment]
Ok. I'm staying tuned!

**Comment by NathanLovato** [comment]
I finally had a bit of time to get to this question! See the current open issues and the README for a start of a reply. If you have more questions or you are lacking information, please ask anytime, reply on the issues… 🙂
