### ISSUE TITLE
Leave dead battlers in the TurnQueue for TurnOrder UI

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-turn-based-rpg#121]
To update itself, the turn order user interface will need to know which characters are dead on the battlefield.
So we need to change the way TurnQueue works to accommodate for that

**Comment by godofgrunts** [comment]
Does it? Why can't they just be removed from the UI?

**Comment by NathanLovato** [comment]
Please check the discussion in the pr

**Comment by GresilleSiffle** [comment]
Hi @godofgrunts 

I think it's a better option to keep all battlers in the turn queue, and to let the UI updates itself according to the battlers state. Currently it's impossible for the UI to know if a battler has just died or left the arena. 

There are a lot a features we could have by keeping all batlers in the queue. First, if a battler is not in the queue, the UI could just removes its portrait and assume he/she has left the arena. Also, if a battler is still in the queue but has 0 HP, its combat portrait could be greyed-out by the UI and still appear in the turn list to remember the player that this character can be revived for example. etc. etc.

By having all battlers in the `TurnQueue` , we can be sure to have in this node a complete representation of the arena and the specific state of each battler. The UI can then react to this, without trying to guess what just happened in the previous turn.

**Comment by GresilleSiffle** [comment]
It seems like the `TurnQueue` does not remove any of its children (the battlers), BUT, they are automatically freed by the method `_on_health_depleted` of `Battler.gd`. 
```gdscript

func _on_health_depleted():
	selectable = false
	yield(skin.play_death(), "completed")
	queue_free()
```

That is why they disappear from the queue, and why the `skip_turn` method of `TurnQueue` is never called.

**Comment by GresilleSiffle** [comment]
I made a very simple test, I confirm that removing the `queue_free()` call allows the `TurnQueue `node to keep all of its children. 

But the battlers skin are still displayed even if the battler is dead : P Sounds like a bug for me. The death animation of the `BattlerAnim` scene should set the alpha property of the battler to 0 right?

![battler animation possible bug](https://user-images.githubusercontent.com/39056254/50002877-eca73a00-ffa1-11e8-9cd5-fc9b763e3436.GIF)

**Comment by GresilleSiffle** [comment]
I've opened an issue for that #128 , and created a pull request #129

**Comment by NathanLovato** [comment]
Visibility should be set to false at the end of the animation, not just alpha to 0
