### ISSUE TITLE
Bug Regression: Mana no longer subtracted with a skill is used.

### ISSUE THREAD

**Issue by godofgrunts** [GDquest/godot-turn-based-rpg#126]
![mana](https://user-images.githubusercontent.com/338843/49881640-dca22580-fdfc-11e8-811b-11492f760696.gif)
Using e6bdcbb (master as of this writing)

**Comment by GresilleSiffle** [comment]
I do not reproduce with the current master 79f4ba51cef21e00540943684ce1937cd1545e5d.

Do you still have the bug?

**Comment by guilhermehto** [comment]
Couldn't reproduce it on d7a4376

**Comment by NathanLovato** [comment]
Can't reproduce either, closing for now
