### ISSUE TITLE
Write the initial game concept

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-turn-based-rpg#13]

**Comment by neogn95** [comment]
I would love to write this. Is there is any starting point or reference based on which this can be initiated?

**Comment by NathanLovato** [comment]
Thanks for your help. As you can see I've already assigned myself to this task. It's one that I couldn't confidently delegate except to an experienced, professional designer. I'll try to draft it later this morning (but first, coffee ☕😄)

**Comment by NathanLovato** [comment]
The next step is to write some more details about the combat mechanics, to have some clear skills and jobs to implement, as we are moving into systems that interact with data and game content

**Comment by NathanLovato** [comment]
The initial concept is shallow. As we're building a tool as well as a mini game here though, I do want to prototype and iterate with code over putting everything on paper from the start, then implementing something different.
