### ISSUE TITLE
Bug: When a skill consumes the remaining mana, the mana bar disappears

### ISSUE THREAD

**Issue by GresilleSiffle** [GDquest/godot-turn-based-rpg#133]
I may have found a bug, if someone can confirm.

It looks like when a mana bar is depleted during a combat, it completely disappears for the duration of the fight. It will appear again at the beginning next combat.

From my point of view, I expected the mana bar to display 0 / 8 for Robi instead of just disappear.

**Comment by GresilleSiffle** [comment]
In the `HookableManaBar`, I found the `HIDE_ON_DEPLETED `exported variable set to `true`.

Maybe there is a reason for that?

**Comment by guilhermehto** [comment]
You're correct, that's the reason. Though, if the desired effect is to hide the manabar when it's depleted, we shouldn't show it again once another encounter starts.
