### ISSUE TITLE
The .gitignore file doesn't ignore all .import files

### ISSUE THREAD

**Issue by GresilleSiffle** [GDquest/godot-turn-based-rpg#135]
Currently not all .import files are ignored, even if the `.import` string is present in our `.gitignore`. As a result, all .import files present in the combat interface are always displayed as untracked by Git.

I think we should ignore `*.import` instead of just `.import` ([see the syntax here](https://git-scm.com/docs/gitignore)).

Gonna make a pull request.

**Comment by NathanLovato** [comment]
As Nicholas says, *.import files store your import settings, which are necessary for the project to import and work properly.

**Comment by GresilleSiffle** [comment]
I didn't know that, thanks! Sorry for the noise : )
