### ISSUE TITLE
Add a base class to represent Magic and/or Skills

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-turn-based-rpg#15]
Create a class that we can use to store all the data related to a special attack a battler can use.

Should this class extend Resource or Reference? We'd use it to store only the data related to a skill (then another Object or Node could use the resource and provide functionality on the Battler, or render it in the UI).
See `StartingStats` https://github.com/GDquest/godot-turn-based-rpg/blob/master/godot/combat/battlers/jobs/StartingStats.gd

**Comment by guilhermehto** [comment]
This was closed through #32 I believe.
