### ISSUE TITLE
Experience and levelling up

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-turn-based-rpg#18]
Add the ability for the characters to gain experience when killing monsters, to level up when they reached a certain amount of experience, and to increase some stats when they level up.

**Comment by NathanLovato** [comment]
See our tutorial https://www.youtube.com/watch?v=V-VJra5lrv0

**Comment by nhydock** [comment]
I'll take on this task.  I plan on adding in stat curves for character definitions to help show off progression from leveling up.

**Comment by NathanLovato** [comment]
Added in https://github.com/GDquest/godot-turn-based-rpg/commit/d9477b9499e045b886a448732e73c27b48a06c6e
