### ISSUE TITLE
Add monster groups/a way to compose encounters

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-turn-based-rpg#21]
We need some way to create groups of monsters to balance the foes the player will face. It's just lists of monsters to start with (e.g. two slimes and a porcupine), with some code to pick a random group among groups that should spawn in a given area on the map.

Currently there's no notion of formations in the game, front or back rows in combat. I think a basic system will be enough for this project.

**Comment by nhydock** [comment]
I'll take on this task

**Comment by NathanLovato** [comment]
@nhydock is working on this in #28
