### ISSUE TITLE
Map: integrate the conversation system

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-turn-based-rpg#22]
Also create an NPC that takes one cell and that the player can interact with. The job is mostly to port your work on the grid-based & conversation demo to Godot 3.1, integrating it in here.

**Comment by henriiquecampos** [comment]
Hey there, just started working on that. Any idea of the personality of the NPC, or am I free to create one from scratch :eyes:

**Comment by NathanLovato** [comment]
It's just about setting up conversation, to test the system and show that it works. Having just a few lines will do the trick for now

**Comment by NathanLovato** [comment]
But look at the game concept, there's 3 characters to pull from. I'll work on some art ASAP

**Comment by henriiquecampos** [comment]
Hmm, I think this is blocked by #27 is there any off-combat gamemplay already?
