### ISSUE TITLE
Implementing Actions

### ISSUE THREAD

**Issue by salvob41** [GDquest/godot-turn-based-rpg#25]
This is an issue to design and implement different actions, such as Healing, Magic, Item, Special (?). 

We could do as it is now for the Attack. Nodes that implements actions.

**Comment by nhydock** [comment]
Might be good to define commands as a resource type that you can attach to things.  This could allow you to more easily define commands that can be shared across multiple types, such as items that can cast magic for characters who can't typically use magic, as well as define monster AI rules that allow them to select their move from a provided list of commands.

**Comment by MarianoGnu** [comment]
FYI I'm working on this issue

**Comment by nhydock** [comment]
@MarianoGnu I was looking at this this morning as well to spruce up how skills are implemented and have some ideas.  Will push up some code to my fork in a few hours if you want to have a look at what I was thinking.
