### ISSUE TITLE
When battle ends return to map

### ISSUE THREAD

**Issue by salvob41** [GDquest/godot-turn-based-rpg#30]
For this, #17 needs to be completed and depending on the outcome of the battle return to the map if at least one of the party member is alive or the Gameover screen if everyone is dead (#29 )

**Comment by salvob41** [comment]
@nhydock, I saw that in your PR you implement the return to map already. Does it handle the Game Over as well?

**Comment by nhydock** [comment]
@salvob41 nope, gameover screen has not yet been handled, though the event is emitted.

**Comment by godofgrunts** [comment]
To add to this, when the players return to the map, the enemy they are facing should be removed from the map if the victory signal is emitted.

Might consider leaving the enemy on the map if some of them run from battle, but I don't think that's strictly needed.

**Comment by NathanLovato** [comment]
The map is currently a placeholder. It needs some design/concept first, there's no content at this point

**Comment by NathanLovato** [comment]
This is already in actually
