### ISSUE TITLE
Map: Prevent Player from moving on the map during battle

### ISSUE THREAD

**Issue by godofgrunts** [GDquest/godot-turn-based-rpg#37]
Currently, during battle, the actor can freely move around the map. This allows the player to initiate multiple battles at the same time and causes a disconnect since the player appears to have randomly teleported while in battle.

**Comment by henriiquecampos** [comment]
I think we can make something like in the Godot rpg-demo, where we remove the map from the process tree, than we insert it again when the combat is over

https://github.com/godotengine/godot-demo-projects/blob/master/2d/role_playing_game/Game.gd#L10-L20

https://github.com/godotengine/godot-demo-projects/blob/master/2d/role_playing_game/Game.gd#L39-L41

Any suggestions on how to handle that @NathanLovato ?

**Comment by NathanLovato** [comment]
closed with #38
