### ISSUE TITLE
Code Guide

### ISSUE THREAD

**Issue by godofgrunts** [GDquest/godot-turn-based-rpg#55]
It's possible my skill set is just too low for projects of this size, but I'm already having a hard time following what the code is doing as we slowly ramped up.

Would it be possible, or even desirable, to have some sort of guide that explains how the code interconnects? 

If so, I think starting it early would be good so it doesn't get overwhelming later.

This might be a good use case for the wiki.

**Comment by guilhermehto** [comment]
There are video tutorials being made and released over on GDQuest's YouTube channel 🙂

They explain the overall structure of the project, focusing on different systems at a time.

**Comment by godofgrunts** [comment]
I'm aware, but, and maybe this is intended as I did learn a lot, this is what I had to go through to figure out how a single turn played out.

![tbrpg-work](https://user-images.githubusercontent.com/338843/49042753-03beed00-f197-11e8-9e2c-54b7a29d64ca.jpg)

Now that I've done the work, it does make more sense and maybe a guide shouldn't be created as you have to teach yourself how the code flows instead of taking a shortcut.

**Comment by NathanLovato** [comment]
As we talked about on Discord, this would take too much extra work to keep the docs in sync with the project. If there were more contributors, sure - but even then, most contributors won't need to dive into the full code.
There'll be an overview of the combat system's code/project architecture for v0.2
