### ISSUE TITLE
Create a repository's Project to keep track of issues' status

### ISSUE THREAD

**Issue by henriiquecampos** [GDquest/godot-turn-based-rpg#63]
Gladly the project is growing at a good pace, in these times we are very likely to start a solution for something being worked on already, or even stepping on eachother's work. We already got some, e.g. #54 

I propose to make a simple, automated, project to keep track of issues and PRs that are:

- still to be done i.e. **To do**
- being worked on i.e. **Doing**
- solved i.e. **Done**

**Comment by NathanLovato** [comment]
So on top of the issues, you're suggesting to add an extra place to check for the issues' status?

I think there's not enough issues and contributors to make it worth it. Even a project the size of Godot doesn't use kaban boards and it works fine with hundreds of contributors. What you need is to get contributors used to always communicate, to mention they're working on this or that issue. godofgrunts just didn't notice Gui was assigned to the task already.

**Comment by NathanLovato** [comment]
I'm leaving this up for discussion but you'll need to come up with really good arguments to convince me. I've worked with kaban boards for clients in the past and it's never worked - it only works if someone updates it daily, and as this someone would have to be me...

**Comment by godofgrunts** [comment]
So as someone who is not a strong programmer, I don't want to hold the development back if I'm trying to figure something out that someone else can do quickly. 

#54 is a great example where it took me something like 7 hours to figure out the solution while the other contributor assigned himself and had a PR in like 3.

My question is how does this sort of thing work on a project so young? There's not a lot of bugs to try and work on and I could see a situation where everyone is waiting on me to try and figure out a solution to an issue (assuming I could even figure it out).

**Comment by guilhermehto** [comment]
Not sure if this is needed, I'd get confused at first if I saw something like this. It would decentralize the information from the repo and I'm not sure if it wouldn't make the problem worse: "I forgot the check the issues repo and started working on this too". Maybe I didn't get the idea correctly, though, if you could elaborate a bit more that would be awesome 🙂

> I could see a situation where everyone is waiting on me to try and figure out a solution to an issue

If this does happen you can always communicate, ask for help, etc.. There's always someone is Discord that will be able to help, or you can push a WIP PR. There's no need to let fear prevent you from working on something you want. And after submitting the PR, there will be people to review your code and let you know where you can improve :)

**Comment by henriiquecampos** [comment]
> it only works if someone updates it daily, and as this someone would have to be me

GitHub has automated templates which moves an issue depending on its status, it's for the most common, and probably time consuming, use cases of a Kanban board.
![image](https://user-images.githubusercontent.com/10171059/49082107-07528280-f230-11e8-87d2-667ac3e1bc60.png)

> Even a project the size of Godot doesn't use kaban boards and it works fine with hundreds of contributors

It was [stated by maintainers](https://github.com/godotengine/godot-roadmap#faq) that the reason why they don't use one is exactly because they are big and have a lot of contributors working on their free time by pure motivation, fact being Godot had a [Roadmap trello back in 2016](https://trello.com/b/Vl7OgSuq/godot-engine-21-outdated). But I don't think size really matters as a way to measure the importance of a project management tool e.g. both big projects as [NodeJS](https://github.com/nodejs/node/projects) with 9 parallel projects, and small ones such as [itch.io's butler](https://github.com/itchio/butler/projects/1) use them.

> So on top of the issues, you're suggesting to add an extra place to check for the issues' status?

They are meant for completely different needs, issue tracker is meant to help contributors, maintainers and users to avoid multiple reports of the same issue and report new issues found in the project it is not meant to be a project management tool, although it can surely be used for that. The Kanban board is meant for task/project management and it's also a good way to to communicate the pace of the project to whoever drop by.

> godofgrunts just didn't notice Gui was assigned to the task already.

It also happened with me on #17 , even tho I was assigned to the issue as well.

> What you need is to get contributors used to always communicate

Completely agree, having a Kanban doesn't prevent communication, I'd say it can improve it without demanding "social" engagement, e.g. to engage in an issue discussion, this is an extra step everyone have to do in order to contribute, I'm not saying a kanban board would prevent this, but it helps setup a minimal knowledge of how is the current state of the project, if this is just what a contributor needs to contribute. Without a kanban they will have to browse the issue tracker open issues and either not realizing a contributor/maintainer was already assigned, as already happened, or engage in the issue discussion which imo is an extra step in a contribution workflow.

But I do agree that this can be a premature step on the project's life cycle, it is meant to fulfil a need, if there aren't any, then I think we can close the issue

**Comment by godofgrunts** [comment]
> or you can push a WIP PR. 

When I do that would I later just squash the commits when I was ready for the full PR?

**Comment by NathanLovato** [comment]
> They are meant for completely different needs, issue tracker [...] it is not meant to be a project management tool

How come? Open and closed tasks, milestones, labels to filter them, assigned developer... that's a project management tool.

I get that cards give you a different view and that it might look friendlier to inexperienced users. But it doesn't solve the issues we have right now:

- Contributors can't take ownership of issues or cards. We can only assign people from the team
- Whether you move the cards manually or use keywords, there's always some extra editing work to do. Who's going to do it when I'm not around? I'm not counting on new contributors to know to update their issues, or to naturally mention they're working on something.

I've met my fair share of developers and interacted in a number of open source project over the past 4 years, and imo there are many contributors who never communicate.

I don't think we have a problem with the project's management at the moment, and I don't think a kaban board solves problems with communication amongst contributors. It can be good when you're developing multiple projects in parallel in the same repo, to keep track of each separately, or when you want to have a roadmap, to give a higher-level view of what the technology is about and which features are planned. But we don't need that either for now.

**Comment by NathanLovato** [comment]
@godofgrunts You can use `git commit --amend` to add your changes to your previous commit, then `git push -f` to overwrite your changes on your fork/branch on GitHub. Otherwise I can squash your commits when I merge the PR.

And yes, opening a [WIP] PR is a great way to show you've started working on an issue, although you should always mention it first on the issue itself to let people who browse the project know

**Comment by NathanLovato** [comment]
No update on this, so closing the discussion for now. Feel free to reopen it if you have something to add, or if in the future the need for new project management tools arises
