### ISSUE TITLE
Map: create leader and follower pawns based on the party

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-turn-based-rpg#90]
Currently the characters on the LocalMap are hard-coded, they're not related to the party. Each pawn should represent a playable character, the leader being the first character in the party, and the others being followers.

The code should also provide a function to clean up and rebuild the pawns when the party order changes (to control a different character)

**Comment by salvob41** [comment]
Also... Spawnposition for players should look up to party members  formation in order to spawn properly (there are two position2D nodes right now)

**Comment by NathanLovato** [comment]
This task is about the map. Let's open another issue for the combat arena
